version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: date && ls -a
    - run: date && ls
    - run: date
    - run: date
    - run: date && ls -a


workflows:
  version: 2
  abas:
    jobs:
    - abas
